# Generated by Django 4.2 on 2023-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=100)),
                ('text2', models.TextField()),
                ('time_create2', models.DateTimeField(auto_now_add=True)),
                ('time_update2', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='musinst',
            old_name='text',
            new_name='text1',
        ),
        migrations.RenameField(
            model_name='musinst',
            old_name='time_create',
            new_name='time_create1',
        ),
        migrations.RenameField(
            model_name='musinst',
            old_name='time_update',
            new_name='time_update1',
        ),
        migrations.RenameField(
            model_name='musinst',
            old_name='title',
            new_name='title1',
        ),
    ]
